### ISSUE TITLE
Hi there, love the guide..

### ISSUE THREAD

**Issue by godzhand** [vStar925/Saints-Row-1-Modding#1]
Hello...nice work...saw this on Twitter..right now I'm banned..I would like to have a chat with you if you don't mind https://saintsrow.net  also you forgot to give credit for the tools, and the zip file... gotta add credit to gibbed of course...

**Comment by vStar925** [comment]
Oh shit, yeah I did. I honestly downloaded so many different tools trying to figure this out I kinda forget where I got that from. I'll edit it and I joined your Discord.
